# Base configs
baseurl: "https://gauravroy48.github.io/BlenderExperiments/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Blender Projects by Gaurav Roy"
subtitle: "Daily experiments with Blender!"
author: "Gaurav Roy"
header:
 title: "Blender Experiments"
 subtitle: "by Gaurav Roy"
footer:
 name: "Hello everyone!"
 bio: "Welcome to my page where I upload the results of my daily Blender Experiments!"
 github: "You can also find my project results on <a href=\"https://www.instagram.com/blenderexperiments\">Instagram</a> :)"
web_design: ""
social_urls:
  instagram: "https://www.instagram.com/blenderexperiments"
  linkedin: "https://www.linkedin.com/in/gauravroy0408"
  github: "https://github.com/GauravRoy48"

theme: jekyll-theme-cayman
